apiVersion: v1
kind: Service
metadata:
  name: team5-frontend
  namespace: skala3-finalproj-class2-team5
  labels:
    app: team5-frontend
spec:
  type: ClusterIP
  selector:
    app: team5-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
