apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team5-iveri
  namespace: skala-argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/SKALA-TEAM5/frontend.git
      targetRevision: main
      path: k8s
    - repoURL: https://github.com/SKALA-TEAM5/db.git
      targetRevision: main
      path: k8s/postgres
    - repoURL: https://github.com/SKALA-TEAM5/db.git
      targetRevision: main
      path: k8s/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: skala3-finalproj-class2-team5
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
